-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Хост: localhost
-- Время создания: Фев 17 2020 г., 20:43
-- Версия сервера: 5.6.39-83.1
-- Версия PHP: 5.6.40

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `cw56468_art`
--

-- --------------------------------------------------------

--
-- Структура таблицы `paintings`
--

CREATE TABLE IF NOT EXISTS `paintings` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `num` int(11) NOT NULL,
  `type` varchar(255) NOT NULL,
  `namerus` text NOT NULL,
  `nameeng` text NOT NULL,
  `descriptionrus` varchar(5000) NOT NULL,
  `description2rus` varchar(500) NOT NULL,
  `descriptioneng` varchar(5000) NOT NULL,
  `description2eng` varchar(500) NOT NULL,
  `materialsrus` varchar(500) NOT NULL,
  `materialseng` varchar(500) NOT NULL,
  `sizerus` varchar(255) NOT NULL,
  `sizeeng` varchar(255) NOT NULL,
  `weight` varchar(11) NOT NULL,
  `statuseng` text NOT NULL,
  `statusrus` text NOT NULL,
  `price` varchar(255) NOT NULL,
  `pricedollar` varchar(11) NOT NULL,
  `img1` varchar(1000) NOT NULL,
  `img2` varchar(1000) NOT NULL,
  `img3` varchar(1000) NOT NULL,
  `img4` varchar(1000) NOT NULL,
  `img5` varchar(1000) NOT NULL,
  `img6` varchar(1000) NOT NULL,
  `img7` varchar(1000) NOT NULL,
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=63 DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `paintings`
--

INSERT INTO `paintings` (`id`, `num`, `type`, `namerus`, `nameeng`, `descriptionrus`, `description2rus`, `descriptioneng`, `description2eng`, `materialsrus`, `materialseng`, `sizerus`, `sizeeng`, `weight`, `statuseng`, `statusrus`, `price`, `pricedollar`, `img1`, `img2`, `img3`, `img4`, `img5`, `img6`, `img7`) VALUES
(1, 900, 'picture', 'Вихрь', 'Whirl', 'Панно рельефное. Абстрактный сюжет.', 'Возможно изготовление в любом цвете.', 'A relief panel. Abstract plot.', 'Manufacturing is possible in any color and size.', 'акриловые краски, контуры объёмные, металлическая фурнитура, хрустальная паста, объёмная паста.', 'acrylic paints, volume contours, metal fittings, crystal paste, volume paste.', '41 * 41 см', '41 * 41 cm', '', 'For sale', 'Продаётся', '5 000', '100', 'portfolio\\reliefpanel-1.jpg\"', 'portfolio\\reliefpanel-2.jpg\"', 'portfolio\\reliefpanel-3.jpg\"', '', '', '', ''),
(2, 800, 'picture', 'Панно настенное \"Луг\"', 'Wall panel \"Meadow\"', '', 'Изготовление возможно в любом цвете и размере.', '', 'Manufacturing is possible in any color and size.', 'гипс, акриловая паста. Основа-дерево.', 'gypsum, acrylic paste. The wooden basis.', 'образца 130 * 130 см', '130 * 130 cm', '', '', '', '0', '', 'portfolio\\meadow-1.jpg\"', 'portfolio\\meadow-2.jpg\"', 'portfolio\\meadow-3.jpg\"', 'portfolio\\meadow-4.jpg\"', '', '', ''),
(3, 500, 'picture', 'Яблоня', 'Apple tree', 'Художественное панно из смальты.', '', 'Artistic panel of smalt.', '', 'смальта ORSONI (Италия), серебристая стеклянная мозаика.\r\nМозаика/микромозаика.\r\nРамка выполнена из стеклянной мозаики.', 'smalt ORSONI (Italy), Silvery glass mosaic.\r\nMosaic / micromosaic. The frame is made of glass mosaic.', '88,5 см * 62,5 см. Толщина 28 мм. Размер тессера от 1 мм.', '88.5 cm * 62.5 cm. Thickness 28 mm. Tesser\'s size is from 1 mm.', '', '', '', '0', '', 'portfolio\\appletree.jpg\"', '', '', '', '', '', ''),
(4, 600, 'picture', 'Сон. Весна. Лето. Осень. Зима. И снова...', 'Dream. Spring. Summer. Autumn. Winter. And again...', 'Художественное панно из смальты.', 'Работа заняла первое место в Мировом Арт-проекте Международная выставка-конкурс \"Зажигая звезды\" в Центральном Доме Художников на Крымском Валу (май 2017г.).', 'Artistic panel of smalt.', 'The work took first place in the World Art Project International exhibition-competition \"Lighting the Stars\" in the Central House of Artists on the Crimean Val (May 2017).', 'Материал: смальта ORSONI (Италия).\r\nМозаика/микромозаика. ', 'smalt ORSONI (Italy).\r\nMosaic / micromosaic.', '56 см * 85 см. Размер тессера от 1 мм.', '56 cm * 85 cm. Tesser\'s size is from 1 mm.', '13.7', 'For sale', 'Продаётся', '150 000', '3 000', 'portfolio\\dream.jpg\"', '', '', '', '', '', ''),
(5, 700, 'picture', 'Дирижёр', 'Conductor', 'Художественное панно из смальты.', '', 'Artistic panel of smalt.', '', 'Материал: смальта ORSONI (Италия). Мозаика/микромозаика.', 'smalt ORSONI (Italy).\r\nMosaic / micromosaic.', '62см * 47см.\r\nТолщина 28 мм.\r\nРазмер тессера от 1 мм.', '62 cm * 47 cm. Thickness 28 mm.\r\nTesser\'s size is from 1 mm.', '', '', '', '0', '', 'portfolio\\conductor.jpg\"', '', '', '', '', '', ''),
(6, 0, 'picture', 'Без остановки', 'Without a stop', 'Триптих.', 'Панно из смальты.', 'Triptych.', 'Artistic panel of smalt.', 'смальта ORSONI (Италия).\r\nМозаика/микромозаика.', 'smalt ORSONI (Italy).\r\nMosaic / micromosaic.', '40см * 120см. (40см * 40см * 3)\r\nРазмер тессера от 1 мм.', '40 cm * 120 cm. (40cm * 40cm * 3)\r\nTesser\'s size is from 1 mm.', '3 * 3.8', 'For sale', 'Продаётся', '120 000', '3 200', 'portfolio\\withoutstop-1.jpg\"', 'portfolio\\withoutstop-2.jpg\"', 'portfolio\\withoutstop-3.jpg\"', 'portfolio\\withoutstop-4.jpg\"', 'portfolio\\withoutstop-5.jpg\"', '', ''),
(7, 400, 'picture', 'Все впереди!', 'Everything is ahead!', 'Картина из смальты.', 'Работа заняла 1 место на Российской неделе Искусств Осень 2018. ', 'Artistic panel of smalt.', 'The work took 1st place in the Russian Art Week Autumn 2018.', 'смальта ORSONI (Италия). Мозаика/микромозаика.', 'smalt ORSONI (Italy).\r\nMosaic / micromosaic.', '56 см * 86 см.\r\nТолщина 28 мм.\r\nРазмер тессера от 1 мм.', '56 cm * 86 cm.\r\nThickness 28 mm.\r\nTesser\'s size is from 1 mm.', '12', 'For sale', 'Продаётся', '150 000', '3 500', 'portfolio\\everythingisahead.jpg\"', '', '', '', '', '', ''),
(8, 300, 'picture', 'Ежи', 'Hedgehogs', 'Картина из смальты.', '', 'Artistic panel of smalt.', '', 'смальта ORSONI (Италия). Мозаика/микромозаика.', 'smalt ORSONI (Italy).\r\nMosaic / micromosaic.', '78 см * 60 см.', '78 cm * 60 cm.', '', '', '', '0', '', 'portfolio\\hedgehogs.jpg\"', '', '', '', '', '', ''),
(9, 100, 'picture', 'Линия прибоя', 'Surf line', 'Художественное панно из смальты.', 'Объемная мозаика.', 'Art panel from smalt.', 'Volumetric mosaic.', 'смальта ORSONI (Италия), песок, цемент, галька.\r\nМозаика/микромозаика. ', 'ORSONI smalt (Italy), sand, cement, pebbles.\r\nMosaic / micromosaic.', '78*58*5 см.\r\nРазмер тессера от 1 мм.', '78*58*5 cm.\r\nTesser\'s size from 1 mm.', '10', 'For sale', 'Продаётся', '95 000', '2 000', 'portfolio\\surfline-1.jpg\"', 'portfolio\\surfline-2.jpg\"', 'portfolio\\surfline-3.jpg\"', 'portfolio\\surfline-4.jpg\"', 'portfolio\\surfline-5.jpg\"', '', ''),
(10, 0, 'figurine', 'Брызги', 'Splash', 'Объёмная микромозаика.', 'Фигура выполнена из глины.\r\nВолосы-стекло. Каждая прядь изготовлена вручную, платье- смальта ORSONI (Италия).', 'Volumetric micromosaic.', 'The figure is made of clay.\r\nHair is glass. Each strand is made by hand, dress-smalt ORSONI (Italy).', 'смальта, камень, смола, стекло, глина, металл.\r\nМозаика/микромозаика.', 'smalt, stone, resin, glass, clay, metal.\r\nMosaic / micromosaic.', 'тессера от 1 мм.\r\nВысота 56 см.', 'of tesser from 1 mm.\r\nHeight 56 cm.', '', 'For sale', 'Продаётся', '50 000', '2 000', 'portfolio\\splash-1.jpg\"', 'portfolio\\splash-2.jpg\"', 'portfolio\\splash-3.jpg\"', 'portfolio\\splash-4.jpg\"', 'portfolio\\splash-5.jpg\"', 'portfolio\\splash-6.jpg\"', ''),
(11, 0, 'figurine', 'Ручей', 'Stream', 'Объемная микромозаика.', 'Работа заняла 1 место на Российской неделе Искусств Осень 2018. Номинация кукла из нетрадиционных материалов.', 'Volumetric micromosaic.', 'The work took 1st place in the Russian Art Week Autumn 2018. Nomination doll from unconventional materials.', 'смальта, полимерная глина, глина, галька, дерево. Фигура выполнена из глины.\r\nВолосы, ковер - смальта ORSONI (Италия). Мозаика/микромозаика.', 'smalt, polymer clay, clay, pebbles, wood.\r\nThe figure is made of clay.\r\nHair, carpet - smalt ORSONI (Italy). Mosaic / micromosaic.', '39 см * 32 см * 32 см. Размер тессера от 1 мм.\r\nВысота 32 см.', '39 cm * 32 cm * 32 cm. Tesser\'s size from 1 mm.\r\nHeight 32 cm.', '6.5', 'For sale', 'Продаётся', '50 000', '2 000', 'portfolio\\stream-1.jpg\"', 'portfolio\\stream-3.jpg\"', 'portfolio\\stream-5.jpg\"', 'portfolio\\stream-2.jpg\"', 'portfolio\\stream-4.jpg\"', '', ''),
(12, 1900, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', '', '', '0', '', 'portfolio\\apple5-1.jpg\"', 'portfolio\\apple5-2.jpg\"', 'portfolio\\apple5-3.jpg\"', 'portfolio\\apple5-4.jpg\"', 'portfolio\\apple5-5.jpg\"', '', ''),
(13, 1800, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', '', '', '0', '', 'portfolio\\apple6-1.jpg\"', 'portfolio\\apple6-2.jpg\"', 'portfolio\\apple6-3.jpg\"', 'portfolio\\apple6-4.jpg\"', 'portfolio\\apple6-5.jpg\"', '', ''),
(14, 1700, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', '', '', '0', '', 'portfolio\\apple13-1.jpg\"', 'portfolio\\apple13-2.jpg\"', 'portfolio\\apple13-3.jpg\"', 'portfolio\\apple13-4.jpg\"', 'portfolio\\apple13-5.jpg\"', 'portfolio\\apple13-6.jpg\"', ''),
(15, 1600, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', '', '', '0', '', 'portfolio\\apple12-1.jpg\"', 'portfolio\\apple12-2.jpg\"', 'portfolio\\apple12-3.jpg\"', 'portfolio\\apple12-4.jpg\"', '', '', ''),
(16, 1500, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', '', '', '0', '', 'portfolio\\apple11-1.jpg\"', 'portfolio\\apple11-2.jpg\"', 'portfolio\\apple11-3.jpg\"', 'portfolio\\apple11-4.jpg\"', 'portfolio\\apple11-5.jpg\"', '', ''),
(18, 1400, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', '', '', '0', '', 'portfolio\\apple10-1.jpg\"', 'portfolio\\apple10-2.jpg\"', 'portfolio\\apple10-3.jpg\"', 'portfolio\\apple10-4.jpg\"', 'portfolio\\apple10-5.jpg\"', '', ''),
(19, 600, 'volumemosaic', 'Яблоко в яблоке', 'Apple in apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '', '', '', '0', '', 'portfolio\\apple9-1.jpg\"', 'portfolio\\apple9-2.jpg\"', 'portfolio\\apple9-3.jpg\"', 'portfolio\\apple9-4.jpg\"', 'portfolio\\apple9-5.jpg\"', '', ''),
(20, 1300, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', '', '', '', '', 'portfolio\\apple8-1.jpg\"', 'portfolio\\apple8-2.jpg\"', 'portfolio\\apple8-3.jpg\"', 'portfolio\\apple8-4.jpg\"', '', '', ''),
(21, 1200, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', '', '', '0', '', 'portfolio\\apple7-1.jpg\"', 'portfolio\\apple7-2.jpg\"', 'portfolio\\apple7-3.jpg\"', 'portfolio\\apple7-4.jpg\"', 'portfolio\\apple7-5.jpg\"', 'portfolio\\apple7-6.jpg\"', ''),
(22, 1100, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', '', '', '', '', 'portfolio\\apple1-1.jpg\"', 'portfolio\\apple1-2.jpg\"', 'portfolio\\apple1-3.jpg\"', 'portfolio\\apple1-4.jpg\"', 'portfolio\\apple1-5.jpg\"', 'portfolio\\apple1-6.jpg\"', ''),
(23, 1000, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', 'For sale', 'Продаётся', '5 000', '150', 'portfolio\\apple2-1.jpg\"', 'portfolio\\apple2-2.jpg\"', 'portfolio\\apple2-3.jpg\"', 'portfolio\\apple2-4.jpg\"', 'portfolio\\apple2-5.jpg\"', 'portfolio\\apple2-6.jpg\"', ''),
(24, 900, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', '', '', '', '', 'portfolio\\apple3-1.jpg\"', 'portfolio\\apple3-2.jpg\"', 'portfolio\\apple3-3.jpg\"', 'portfolio\\apple3-4.jpg\"', '', '', ''),
(25, 800, 'volumemosaic', 'Яблоко', 'Apple', '', '', '', '', 'смальта ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '~ 9см', '~ 9cm', '0.3 - 0.4', 'For sale', 'Продаётся', '5 000', '150', 'portfolio\\apple4-1.jpg\"', 'portfolio\\apple4-2.jpg\"', 'portfolio\\apple4-3.jpg\"', 'portfolio\\apple4-4.jpg\"', '', '', ''),
(27, 50, 'volumemosaic', 'Лягушка', 'Frog', 'Объёмная микромозаика.', 'Лягушка из смальты.\r\nПодставка из морской гальки.', 'Volumetric micromosaic.', 'Smalt frog.\r\nStand of sea pebbles.', 'смальта ORSONI (Италия), полимерная глина.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay.\r\nMosaic / micromosaic.', 'тессеров 1-3 мм.\r\nДиаметр 22,5 см, высота 11 см.', 'of the tessers is 1-3 mm.\r\nDiameter 22.5 cm, height 11 cm.', '1.5', 'For sale', 'Продаётся', '10 000', '300', 'portfolio\\frog-1.jpg\"', 'portfolio\\frog-2.jpg\"', 'portfolio\\frog-3.jpg\"', 'portfolio\\frog-4.jpg\"', '', '', ''),
(28, 700, 'volumemosaic', 'Груша', 'Pear', '', '', '', '', 'смальты ORSONI (Италия), полимерная глина, дерево.\r\nМозаика/микромозаика.', 'smalts ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', '15 см * 8 см * 8 см', '15 cm * 8 cm * 8 cm', '0.3 - 0.4', 'For sale', 'Продаётся', '5 000', '150', 'portfolio\\pear-1.jpg\"', 'portfolio\\pear-2.jpg\"', 'portfolio\\pear-3.jpg\"', '', '', '', ''),
(29, 500, 'volumemosaic', 'Лист', 'Leaf', 'Объемная микромозаика.', '', 'Volumetric micromosaic.', '', 'смальта ORSONI (Италия), полимерная глина.\r\nМозаика/микромозаика.', 'smalt ORSONI (Italy), polymer clay.\r\nMosaic / micromosaic.', '30 см * 14 см * 6 см.', '30 cm * 14 cm * 6 cm.', '0.28', 'For sale', 'Продаётся', '6 000', '200', 'portfolio\\leaf.jpg\"', '', '', '', '', '', ''),
(30, 150, 'volumemosaic', 'Ёж', 'Hedgehog', '', 'Объёмная микромозаика. Подставка - спил дуба.', '', 'Volume micromosaic. Stand - slab of oak.', 'смальта ORSONI (Италия), полимерная глина.\r\nМозаика/микромозаика.', 'smalt ORSONI (Italy), polymer clay, wood.\r\nMosaic / micromosaic.', 'тессеров 1-3 мм.\r\nДиаметр 22 см.', 'of tessers 1-3 mm.\r\nDiameter 22 cm.', '0.5', 'For sale', 'Продаётся', '10 000', '200', 'portfolio\\hedgehog-1.jpg\"', 'portfolio\\hedgehog-2.jpg\"', '', '', '', '', ''),
(31, 100, 'volumemosaic', 'Черепаха', 'Turtle', 'Объёмная микромозаика.', '', 'Volumetric micromosaic.', '', 'смальта ORSONI (Италия), камень, песок, галька.\r\n\r\n', 'smalt ORSONI (Italy), stone, sand, pebbles.', 'тессеров 1-3 мм.\r\nДиаметр 27 см. Высота 12 см.', 'of tessers 1-3 mm.\r\nHeight 12 cm. Diameter 27 cm.', '3.5', '', '', '10 000', '300', 'portfolio\\turtle-1.jpg\"', 'portfolio\\turtle-2.jpg\"', 'portfolio\\turtle-3.jpg\"', 'portfolio\\turtle-4.jpg\"', '', '', ''),
(32, 100, 'other', 'Цветочные часы', 'Flower clock', '', '', '', '', 'смальта ORSONI (Италия), хрустальная паста и стекло.\r\nМозаика/микромозаика.', 'smalt ORSONI (Italy), crystal paste and glass.\r\nMosaic / micromosaic.', '45 см * 45 см.', '45 cm * 45cm.', '', 'For sale', 'Продаётся', '10 000', '250', 'portfolio\\flowerclock.jpg\"', '', '', '', '', '', ''),
(33, 30, 'furniture', 'Табурет / Журнальный столик', 'Stool / Coffee table', 'Массив дуба, слегка беленый, отшлифован, отполирован, покрыт маслом с твердым воском. Одна сторона браширована и покрыта темным маслом.\r\n\r\nДекорирован смальтой.', '', 'Oak stump, lightly bleached, polished, covered with oil with solid wax.\r\nOne side is stitched and covered with dark oil.\r\n\r\nIt is decorated with smalt.', '', 'смальта, масло, массив дуба.', 'smalt, oil, solid oak.', '', '', '', '', '', '0', '', 'portfolio\\redstump-1.jpg\"', 'portfolio\\redstump-2.jpg\"', 'portfolio\\redstump-3.jpg\"', 'portfolio\\redstump-4.jpg\"', 'portfolio\\redstump-5.jpg\"', 'portfolio\\redstump-6.jpg\"', ''),
(34, 60, 'furniture', 'Табурет/Журнальный столик', 'Stool / Coffee table', 'Массив дуба, слегка беленый, отшлифован, отполирован, покрыт маслом с твердым воском.', 'Декорирован смальтой.', 'Solid oak, lightly bleached, polished, covered with oil with solid wax.\r\n\r\nOne side is stitched and covered with dark oil.', 'Decorated with smalt.', 'массив дуба, смальта ORSONI (Италия).', 'smalt ORSONI (Italy), oak.', '29*29*37,5 см.', '29*29*37.5 cm.', '', '', '', '0', '', 'portfolio\\greyquarestump-1.jpg\"', 'portfolio\\greyquarestump-2.jpg\"', 'portfolio\\greyquarestump-3.jpg\"', 'portfolio\\greyquarestump-4.jpg\"', 'portfolio\\greyquarestump-5.jpg\"', '', ''),
(35, 50, 'furniture', 'Табурет/Журнальный столик', 'Stool / Coffee table', 'Массив березы, покрыт золотой краской. Бока брашированы. Декорирован смальтой.', 'Высота 48 см.', 'Solid birch, decorated with smalt and glass mosaic.', 'Height 48 cm.', 'массив берёзы, стеклянная мозаика, смальта ORSONI (Италия), краска по дереву.', 'solid birch, glass mosaic, smalt ORSONI (Italy), wood paint.', '', '', '', '', '', '0', '', 'portfolio\\goldenstump-1.jpg\"', 'portfolio\\goldenstump-2.jpg\"', 'portfolio\\goldenstump-3.jpg\"', '', '', '', ''),
(36, 10, 'furniture', 'Табурет/Журнальный столик', 'Stool / Coffee table', 'Массив дуба, декорирован смальтой.', 'Высота 37 см.', 'Solid oak decorated with smalt', 'Height 37 cm.', 'массив дуба, стеклянная мозаика, смальта ORSONI (Италия).', 'solid oak, glass mosaic, smalt ORSONI (Italy).', '', '', '', '', '', '0', '', 'portfolio\\bluestump-1.jpg\"', 'portfolio\\bluestump-2.jpg\"', 'portfolio\\bluestump-3.jpg\"', 'portfolio\\bluestump-4.jpg\"', 'portfolio\\bluestump-5.jpg\"', 'portfolio\\bluestump-6.jpg\"', 'portfolio\\bluestump-7.jpg\"'),
(37, 40, 'furniture', 'Табурет/Журнальный столик', 'Stool / Coffee table', 'Массив дуба, слегка беленый, отшлифован, отполирован, покрыт маслом с твердым воском. Декорирован смальтой.', '', 'Solid oak, slightly bleached, sanded, polished, coated with hard wax oil. Decorated with smalt.', '', 'смальта ORSONI (Италия), масло, массив дуба.', 'smalt ORSONI (Italy), oil, solid oak.', '29*29 см.\r\nВысота 37,5 см.', '29 * 29 cm.\r\nHeight 37.5 cm.', '', '', 'Продаётся', '20 000', '', 'portfolio\\bluesquarestump-1.jpg\"', 'portfolio\\bluesquarestump-2.jpg\"', 'portfolio\\bluesquarestump-3.jpg\"', 'portfolio\\bluesquarestump-4.jpg\"', 'portfolio\\bluesquarestump-5.jpg\"', 'portfolio\\bluesquarestump-6.jpg\"', ''),
(38, 400, 'other', 'Подставка под горячее', 'Stand', 'Спил дуба, отшлифован, отполирован, покрыт маслом с твердым воском. Декорирован смальтой и золотой мозаикой.', '', 'Slab of oak, sanded, polished, coated with solid wax oil. Decorated with smalt and gold mosaic.', '', 'Дуб, смальта ORSONI (Италия), масло osmo, золотая мозаика.', 'Oak, smalt ORSONI (Italy), osmo oil, golden mosaic.', '23 * 20 * 4,5 см.', '23 * 20 * 4,5 cm.', '1.2', '', '', '2 500', '', 'portfolio\\slab1.jpg\"', 'portfolio\\slab.jpg\"', '', '', '', '', ''),
(39, 600, 'other', 'Подставка под горячее', 'Stand', 'Спил дуба, отшлифован, отполирован, покрыт маслом с твердым воском. Декорирован смальтой и золотой мозаикой.', '', 'Slab of oak, sanded, polished, coated with solid wax oil. Decorated with smalt and gold mosaic.', '', 'дуб, смальта ORSONI (Италия), масло osmo, золотая мозаика.', 'oak, smalt ORSONI (Italy), osmo oil, golden mosaic.', '23*20*4,5 см.', '23*20*4,5 cm.', '1.2', '', '', '2 500', '', 'portfolio\\slab2.jpg\"', 'portfolio\\slab.jpg\"', '', '', '', '', ''),
(40, 500, 'other', 'Подставка под горячее', 'Stand', 'Спил дуба, отшлифован, отполирован, покрыт маслом с твердым воском. Декорирован смальтой и золотой мозаикой.', '', 'Slab of oak, sanded, polished, coated with solid wax oil. Decorated with smalt and gold mosaic.', '', 'дуб, смальта ORSONI (Италия), масло osmo, золотая мозаика.', 'oak, smalt ORSONI (Italy), osmo oil, golden mosaic.', '23 * 20 * 4,5 см.', '23 * 20 * 4,5 cm.', '1.2', '', '', '2 500', '', 'portfolio\\slab3.jpg\"', 'portfolio\\slab.jpg\"', '', '', '', '', ''),
(41, 700, 'other', 'Подставка', 'Stand', 'Спил дуба, отшлифован, отполирован, покрыт маслом с твердым воском. Декорирован смальтой.', '', 'Slab of oak, sanded, polished, coated with solid wax oil. Decorated with smalt.', '', 'дуб, смальта ORSONI (Италия), масло osmo.', 'oak, smalt ORSONI (Italy), osmo oil.', '23 * 20 * 4,5 см.', '23 * 20 * 4,5 cm.', '1.2', '', 'Продаётся', '2 000', '', 'portfolio\\slab4-1.jpg\"', 'portfolio\\slab4-2.jpg\"', '', '', '', '', ''),
(42, 300, 'other', 'Корни березы, декорированные смальтой.', 'Roots of birch decorated with smalt.', '', 'Высота 41 см', '', 'Height 41 cm.', 'корни березы, масло, галька, смальта ORSONI (Италия).', 'birch roots, oil, pebbles, smalt ORSONI (Italy).', '', '', '', '', 'Продаётся', '2 000', '', 'portfolio\\sticks2.jpg\"', '', '', '', '', '', ''),
(46, 20, 'furniture', 'Табурет/Журнальный столик', 'Stool / Coffee table', 'Массив берёзы. Бока брашированы. Декорирован смальтой.', 'Высота 48 см.', 'Solid birch, decorated with smalt and glass mosaic.', 'Height 48 cm.', 'массив берёзы, стеклянная мозаика, смальта ORSONI (Италия), лак.', 'solid birch, glass mosaic, smalt ORSONI (Italy), varnish, wood paint.', '', '', '', '', 'Продаётся', '15 000', '', 'portfolio\\brownstump-1.jpg\"', 'portfolio\\brownstump-2.jpg\"', 'portfolio\\brownstump-3.jpg\"', '', '', '', ''),
(43, 200, 'other', 'Коряга, декорированная смальтой', 'Snag, decorated with smalt', '', '', '', '', 'смальта ORSONI (Италия), масло, сосна, стеклянная мозаика.', 'smalt ORSONI (Italy), oil, pine, glass mosaic.', '72 * 28 * 15 см.', '72 * 28 * 15 cm.', '', '', 'Продаётся', '2 500', '', 'portfolio\\sticks1-1.jpg\"', 'portfolio\\sticks1-2.jpg\"', '', '', '', '', ''),
(47, 10, 'picture', 'withoutstop1', '', '', '', '', '', '', '', '', '', '', '', '', '0', '', 'portfolio\\withoutstop-2.jpg\"', '', '', '', '', '', ''),
(48, 11, 'picture', 'withoutstop2', '', '', '', '', '', '', '', '', '', '', '', '', '0', '', 'portfolio\\withoutstop-3.jpg\"', '', '', '', '', '', ''),
(49, 12, 'picture', 'withoutstop3', '', '', '', '', '', '', '', '', '', '', '', '', '0', '', 'portfolio\\withoutstop-4.jpg\"', '', '', '', '', '', ''),
(62, 75, 'picture', 'Пять минут до пробуждения', 'Five minuts before waking up', 'Абстракция. Часть первая триптиха.', 'Объёмная мозаика / микромозаика.', 'Abstraction. The first part of triptych.', 'Volumetric mosaic / micromosaic.', 'смальта ORSONI (Италия), камень, плавленое листовое стекло, металл. Мозаика/микромозаика.', 'ORSONI smalt (Italy), stone, metal, fused sheet glass. Mosaic / micromosaic.', '70*70 см.', '70*70 cm.', '', '', '', '', '', 'portfolio\\fiveminutsbeforewakingup.jpg\"', '', '', '', '', '', ''),
(56, 50, 'other', 'Часы настенные', 'Wall clock', 'Диаметр 45 см', '', 'Diameter 45 cm', '', 'смальта ORSONI (Италия), стекло, латунь.', 'smalt ORSONI (Italy), glass, brass.', '', '', '', 'For sale', 'Продаётся', '35 000', '750', 'portfolio\\butterflyclock-1.jpg\"', 'portfolio\\butterflyclock-2.jpg\"', 'portfolio\\butterflyclock-3.jpg\"', 'portfolio\\butterflyclock-4.jpg\"', 'portfolio\\butterflyclock-5.jpg\"', 'portfolio\\butterflyclock-6.jpg\"', 'portfolio\\butterflyclock-7.jpg\"'),
(50, 400, 'volumemosaic', 'Одуванчик', 'Dandelion', 'Объёмная микромозаика.', '', 'Volumetric micromosaic.', '', 'смальта, стекло, латунь.', 'smalt, glass, brass.', '34 * 17 см', '34 * 17 cm', '', '', '', '', '', 'portfolio\\dandelion5-1.jpg\"', 'portfolio\\dandelion5-2.jpg\"', '', '', '', '', ''),
(51, 300, 'volumemosaic', 'Одуванчик', 'Dandelion', 'Объёмная микромозаика.', '', 'Volumetric micromosaic.', '', 'смальта, стекло, латунь.', 'smalt, glass, brass.', '31 * 17 см', '31 * 17 cm', '', '', '', '', '', 'portfolio\\dandelion4-1.jpg\"', 'portfolio\\dandelion4-2.jpg\"', 'portfolio\\dandelion4-3.jpg\"', 'portfolio\\dandelion4-4.jpg\"', 'portfolio\\dandelion4-5.jpg\"', '', ''),
(53, 200, 'volumemosaic', 'Одуванчики', 'Dandelions', 'Триптих. Объёмная микромозаика.', 'Диаметр каждого ~ 17 см. Высота ~ 32 см.', 'Triptych. Volumetric micromosaic.', 'Diameter of each one is ~ 17 cm. Height ~ 32 cm.', 'смальта, стекло, латунь.', 'smalt, glass, brass.', '', '', '', '', '', '', '', 'portfolio\\dandelion8-2.jpg\"', 'portfolio\\dandelion8-1.jpg\"', 'portfolio\\dandelion3-1.jpg\"', 'portfolio\\dandelion3-4.jpg\"', 'portfolio\\dandelion3-5.jpg\"', '', ''),
(54, 200, 'picture', 'Воспоминания', 'Memories', 'Картина из смальты.', 'До 24 ноября работа находится в Palazzo Rasponi dalle Teste (Равенна) на Биеннале современной мозаики OPERE dal MONDO.', 'Artistic panel of smalt.', 'Until the 24th of November mosaic is located in Palazzo Rasponi dalle Teste (Ravenna), Biennale di mosaico contemporaneo vi edizione OPERE dal MONDO.', 'смальта ORSONI (Италия), стекло, галька, металл. Мозаика/микромозаика. ', 'ORSONI smalt (Italy), pebbles, glass, metal. Mosaic / micromosaic.', '86 см * 60 см. Толщина 2 см.', '86 cm * 60 cm. Thickness 2 cm.', '', '', '', '', '', 'portfolio\\memories-1.jpg\"', 'portfolio\\memories-4.jpg\"', 'portfolio\\memories-7.jpg\"', 'portfolio\\memories-6.jpg\"', '', '', ''),
(55, 50, 'picture', 'Бабочки в животе...', 'Butterflies in the stomach...', 'Картина из смальты', 'Объёмная мозаика / микромозаика.', 'Art panel of smalt.', 'Volumetric mosaic / micromosaic.', 'смальта ORSONI (Италия), галька, металл, стекло, цемент. Мозаика/микромозаика.', 'ORSONI smalt (Italy), pebbles, metal, glass, cement. Mosaic / micromosaic.', '69.5 * 85 * 6 см', '69.5 * 85 * 6 cm', '', '', '', '', '', 'portfolio\\butterflies-1.jpg\"', 'portfolio\\butterflies-2.jpg\"', 'portfolio\\butterflies-3.jpg\"', 'portfolio\\butterflies-4.jpg\"', 'portfolio\\butterflies-5.jpg\"', 'portfolio\\butterflies-6.jpg\"', 'portfolio\\butterflies-7.jpg\"'),
(57, 220, 'volumemosaic', 'Розовый одуванчик', 'Pink dandelion', 'Объёмная микромозаика.', 'Диаметр 17 см, высота 30 см', 'Volumetric micromosaic.', 'Diameter 17 cm, height 30 cm', 'смальта ORSONI (Италия), стекло, латунь.', 'smalt ORSONI (Italy), glass, brass.', '', '', '', 'For sale', 'Продаётся', '6 000', '200', 'portfolio\\pinkdandelion-1.jpg\"', 'portfolio\\pinkdandelion-2.jpg\"', 'portfolio\\pinkdandelion-3.jpg\"', 'portfolio\\pinkdandelion-4.jpg\"', 'portfolio\\pinkdandelion-5.jpg\"', 'portfolio\\pinkdandelion-6.jpg\"', ''),
(58, 250, 'volumemosaic', 'Одуванчик', 'Dandelion', 'Объёмная микромозаика.', 'Диаметр 12.5 см, высота 37 см', 'Volumetric micromosaic.', 'Diameter 12.5 cm, height 37 cm', 'стекло, латунь.', 'glass, brass.', '', '', '', 'For sale', 'Продаётся', '6 000', '200', 'portfolio\\dandelion7-1.jpg\"', 'portfolio\\dandelion7-2.jpg\"', 'portfolio\\dandelion7-3.jpg\"', '', '', '', ''),
(59, 270, 'volumemosaic', 'Одуванчик', 'Dandelion', 'Объёмная микромозаика.', 'Диаметр 17 см, высота 32 см', 'Volumetric micromosaic.', 'Diameter 17 cm, height 32 cm', 'смальта ORSONI (Италия), стекло, латунь.', 'smalt ORSONI (Italy), glass, brass.', '', '', '', 'For sale', 'Продаётся', '6 000', '200', 'portfolio\\dandelion6-1.jpg\"', 'portfolio\\dandelion6-2.jpg\"', 'portfolio\\dandelion6-3.jpg\"', 'portfolio\\dandelion6-4.jpg\"', 'portfolio\\dandelion6-5.jpg\"', '', ''),
(60, 150, 'other', 'Часы настенные', 'Wall clock', 'Диаметр 30 см. Толщина 4.5 см.', '', 'Diameter 30 cm. Thickness 4.5 cm.', '', 'смальта ORSONI (Италия), стекло, латунь.', 'smalt ORSONI (Italy), glass, brass.', '', '', '', '', '', '', '', 'portfolio\\clock1-1.jpg\"', 'portfolio\\clock1-2.jpg\"', '', '', '', '', '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
